### ISSUE TITLE
loading dependent modules

### ISSUE THREAD

**Issue by stephenturner** [ISUgenomics/ProjectModules#1]
Add functionality + documentation for managing dependencies. E.g., https://github.com/tseemann/snippy requires both FreeBayes and samtools 1.1, where samtools 1.3 will not work. Rather than `module load snippy freebayes samtools/1.1`, want to just `module load snippy`. Surely this is possible with modules, but would be nice to wrap this functionality in `mod`.

**Comment by isugif** [comment]
You just need to add

module load samtools/1.1
module load freebayes

into the snippy module file

I do have a mod moduleload command to do this.

mod moduleload snippy samtools/1.1
mod moduleload snippy freebayes

Andrew
Scientist I
Genome Informatics Facility
Office of Biotechnology
206 Science I
Iowa State University
Ames, Iowa 50011
(515)-294-1320

**Comment by stephenturner** [comment]
Nice, thanks.
